namespace Zentory.Application.Projects.DTOs;

public record ProjectSummaryDto(
    Guid      Id,
    string    Code,
    string    Name,
    Guid      ClientId,
    string    ClientName,
    string    Status,
    string    BillingType,
    decimal   ContractValue,
    string    Currency,
    int       HoursTotal,
    int       HoursUsed,
    int       Progress,
    int       HealthScore,
    string    HealthStatus,
    DateTime? StartDate,
    DateTime? EndDate,
    string?   Type = null);

public record ProjectDto(
    Guid      Id,
    string    Code,
    string    Name,
    Guid      ClientId,
    string    ClientName,
    string    Status,
    string    BillingType,
    decimal   ContractValue,
    string    Currency,
    int       HoursTotal,
    int       HoursUsed,
    int       Progress,
    int       HealthScore,
    string    HealthStatus,
    DateTime? StartDate,
    DateTime? EndDate,
    Guid?     ProposalId,
    DateTime  CreatedAt,
    DateTime  UpdatedAt,
    string?   Type = null);
